// Generated by gencpp from file pose_estimator/pipe_pose.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATOR_MESSAGE_PIPE_POSE_H
#define POSE_ESTIMATOR_MESSAGE_PIPE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pose_estimator
{
template <class ContainerAllocator>
struct pipe_pose_
{
  typedef pipe_pose_<ContainerAllocator> Type;

  pipe_pose_()
    : header()
    , pipe_x(0.0)
    , pipe_y(0.0)
    , pipe_z(0.0)
    , pipe_theta_x(0.0)
    , pipe_theta_y(0.0)
    , pipe_theta_z(0.0)  {
    }
  pipe_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pipe_x(0.0)
    , pipe_y(0.0)
    , pipe_z(0.0)
    , pipe_theta_x(0.0)
    , pipe_theta_y(0.0)
    , pipe_theta_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pipe_x_type;
  _pipe_x_type pipe_x;

   typedef float _pipe_y_type;
  _pipe_y_type pipe_y;

   typedef float _pipe_z_type;
  _pipe_z_type pipe_z;

   typedef float _pipe_theta_x_type;
  _pipe_theta_x_type pipe_theta_x;

   typedef float _pipe_theta_y_type;
  _pipe_theta_y_type pipe_theta_y;

   typedef float _pipe_theta_z_type;
  _pipe_theta_z_type pipe_theta_z;





  typedef boost::shared_ptr< ::pose_estimator::pipe_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_estimator::pipe_pose_<ContainerAllocator> const> ConstPtr;

}; // struct pipe_pose_

typedef ::pose_estimator::pipe_pose_<std::allocator<void> > pipe_pose;

typedef boost::shared_ptr< ::pose_estimator::pipe_pose > pipe_posePtr;
typedef boost::shared_ptr< ::pose_estimator::pipe_pose const> pipe_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_estimator::pipe_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_estimator::pipe_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pose_estimator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'pose_estimator': ['/home/erlendb/Programmering/Master/test_ws/src/pose_estimator/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimator::pipe_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimator::pipe_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimator::pipe_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimator::pipe_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimator::pipe_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimator::pipe_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_estimator::pipe_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51eaea2844bf3b987e1fb67e8d6ca8e2";
  }

  static const char* value(const ::pose_estimator::pipe_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51eaea2844bf3b98ULL;
  static const uint64_t static_value2 = 0x7e1fb67e8d6ca8e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_estimator::pipe_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_estimator/pipe_pose";
  }

  static const char* value(const ::pose_estimator::pipe_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_estimator::pipe_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 pipe_x\n\
float32 pipe_y\n\
float32 pipe_z\n\
float32 pipe_theta_x\n\
float32 pipe_theta_y\n\
float32 pipe_theta_z\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pose_estimator::pipe_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_estimator::pipe_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pipe_x);
      stream.next(m.pipe_y);
      stream.next(m.pipe_z);
      stream.next(m.pipe_theta_x);
      stream.next(m.pipe_theta_y);
      stream.next(m.pipe_theta_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pipe_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_estimator::pipe_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_estimator::pipe_pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pipe_x: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_x);
    s << indent << "pipe_y: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_y);
    s << indent << "pipe_z: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_z);
    s << indent << "pipe_theta_x: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_theta_x);
    s << indent << "pipe_theta_y: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_theta_y);
    s << indent << "pipe_theta_z: ";
    Printer<float>::stream(s, indent + "  ", v.pipe_theta_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_ESTIMATOR_MESSAGE_PIPE_POSE_H
